#飞行价格（每秒计）
FlyCostsPerSec: 10
#飞行起步价
FlyCostsStart: 1000
#传送花费倍率（价格=距离*倍率）
TeleportCosts: 0.5
#死亡不掉落保护价格
KeepInventoryCosts: 100
#跨维度传送价格
CrossDimensionTeleportCosts: 1000
# 传送锚-公共锚价格
Costs.PortalAnchor.Public: 1000
# 传送锚-私人锚价格
Costs.PortalAnchor.Private: 300
# 传送锚-商业锚价格
Costs.PortalAnchor.Commercial: 1000
# 超出飞行范围价格倍率
Costs.OutOfFlyArea: 3

#最大飞行距离
Distance.Fly: 80

#飞行CD
CD.Fly: 60
#扫地CD
CD.Clean: 300

# Mysql功能区
Mysql.Username: username
Mysql.password: 123456
Mysql.Address: 127.0.0.1
Mysql.Port: 3306
Mysql.DataBaseName: database

#用户默认设置区
PlayerDefaultConfig.isKeepInventoryEnabled: false

# 传送锚设置
PortalAnchor.MaxPerUser: 10


