name: ECSAssistant
version: 1.0
main: ecsassistant.ecsassistant.ECSAssistant
api-version: 1.18
depend: [ Vault, Essentials, GroupManager ]
authors: [ Ender ]
description: ECS assistant plugin used for custom function.
website: http://enderspro.xyz/
commands:
  flyx:
    aliases:
      - flyx
    description: A command that let user to fly.
    permission: ecs.flyx
    permission-message: You need to have the permission to use this command. Please contact your server OP.
  tpx:
    description: A command that enable user to teleport.
    permission: ecs.tpx
    permission-message: You need to have the permission to use this command. Please contact your server OP.
  ecsadmin:
    description: A command designed for op in ECS.
    permission: ecs.admin
    permission-message: You need to have the permission to use this command. Please contact your server OP.
  keepinventory:
    aliases:
      - ki
    description: A command to let user protect thier inventory.
    permission: ecs.keepinventory
    permission-message: You need to have the permission to use this command. Please contact your server OP.
permissions:
  ecs.flyx:
    description: fly
    default: true
  ecs.tpx:
    description: tp
    default: true
  ecs.admin:
    description: admin
    default: op
  ecs.keepinventory:
    description: inventory protect
    default: true