name: ECSAssistant
version: 1.0
main: ecsassistant.ecsassistant.ECSAssistant
api-version: 1.18
depend: [ Vault, Essentials, GroupManager ]
authors: [ Ender ]
description: ECS assistant plugin used for custom function.
website: http://enderspro.xyz/
commands:
  flyx:
    aliases:
      - flyx
    description: A command that let user to fly.
    permission: ecs.flyx
    permission-message: You need to have the permission to use this command. Please contact your server OP.
permissions:
  ecs.flyx:
    description: fly
    default: true
